version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
      # если используешь кастомный php.ini:
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/zz-app.ini:ro
    depends_on:
      - db
    networks: [wallet]

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [wallet]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # (опционально) автоинициализация БД из sql-файлов:
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    networks: [wallet]

volumes:
  pgdata:

networks:
  wallet:
